-- MySQL Script generated by MySQL Workbench
-- 08/10/15 13:33:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `store` ;

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store` DEFAULT CHARACTER SET utf8 ;
USE `store` ;

-- -----------------------------------------------------
-- Table `store`.`bonus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`bonus` ;

CREATE TABLE IF NOT EXISTS `store`.`bonus` (
  `bonus_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sum_bound` DOUBLE NULL DEFAULT NULL,
  `percentage` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`bonus_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`client` ;

CREATE TABLE IF NOT EXISTS `store`.`client` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bonus_id` VARCHAR(45) NULL DEFAULT NULL,
  `avatar` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`company` ;

CREATE TABLE IF NOT EXISTS `store`.`company` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(50) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `director` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_company_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`feedback` ;

CREATE TABLE IF NOT EXISTS `store`.`feedback` (
  `feedback_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_catalog_unit_id` INT(11) NULL DEFAULT NULL,
  `client_id` INT(11) NULL DEFAULT NULL,
  `text` VARCHAR(512) NULL DEFAULT NULL,
  `feedback_date` DATETIME NULL DEFAULT NULL,
  `rating` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`feedback_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`module`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`module` ;

CREATE TABLE IF NOT EXISTS `store`.`module` (
  `module_id` INT(11) NOT NULL AUTO_INCREMENT,
  `storage_module_unit_id` INT(11) NULL DEFAULT NULL,
  `provider_id` INT(11) NULL DEFAULT NULL,
  `module_type` VARCHAR(50) NULL DEFAULT NULL,
  `image` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`module_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`order_unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`order_unit` ;

CREATE TABLE IF NOT EXISTS `store`.`order_unit` (
  `order_unit_id` INT(11) NOT NULL AUTO_INCREMENT,
  `state_id` INT(11) NULL DEFAULT NULL,
  `order_id` INT(11) NULL DEFAULT NULL,
  `product_catalog_unit_id` INT(11) NULL DEFAULT NULL,
  `order_unit_cost` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`order_unit_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`orders` ;

CREATE TABLE IF NOT EXISTS `store`.`orders` (
  `order_id` INT(11) NOT NULL AUTO_INCREMENT,
  `client_id` INT(11) NULL DEFAULT NULL,
  `payment_scheme_id` INT(11) NULL DEFAULT NULL,
  `order_date` DATETIME NULL DEFAULT NULL,
  `execution_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`payment` ;

CREATE TABLE IF NOT EXISTS `store`.`payment` (
  `payment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NULL DEFAULT NULL,
  `payment_date` DATETIME NULL DEFAULT NULL,
  `payment_sum` DOUBLE NULL DEFAULT NULL,
  `payment_status` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`payment_form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`payment_form` ;

CREATE TABLE IF NOT EXISTS `store`.`payment_form` (
  `payment_type_id` INT(11) NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`payment_type_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`payment_scheme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`payment_scheme` ;

CREATE TABLE IF NOT EXISTS `store`.`payment_scheme` (
  `payment_scheme_id` INT(11) NOT NULL AUTO_INCREMENT,
  `payment_type_id` INT(11) NULL DEFAULT NULL,
  `term` INT(11) NULL DEFAULT NULL,
  `penalty` DOUBLE NULL DEFAULT NULL,
  `number_of_payments` INT(11) NULL DEFAULT NULL,
  `interest_rate` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`payment_scheme_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`product_catalog_unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`product_catalog_unit` ;

CREATE TABLE IF NOT EXISTS `store`.`product_catalog_unit` (
  `product_catalog_unit_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sale_id` INT(11) NULL DEFAULT NULL,
  `product_name` VARCHAR(50) NULL DEFAULT NULL,
  `product_cost` DOUBLE NULL DEFAULT NULL,
  `margin_coefficient` DOUBLE NULL DEFAULT NULL,
  `image` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`product_catalog_unit_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`product_template`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`product_template` ;

CREATE TABLE IF NOT EXISTS `store`.`product_template` (
  `product_template_id` INT(11) NOT NULL AUTO_INCREMENT,
  `product_catalog_unit_id` INT(11) NULL DEFAULT NULL,
  `module_id` INT(11) NULL DEFAULT NULL,
  `modules_number` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`product_template_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`provider` ;

CREATE TABLE IF NOT EXISTS `store`.`provider` (
  `provider_id` INT(11) NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `provider_email` VARCHAR(50) NULL DEFAULT NULL,
  `zip_code` VARCHAR(50) NULL DEFAULT NULL,
  `provider_login` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`provider_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`request` ;

CREATE TABLE IF NOT EXISTS `store`.`request` (
  `request_id` INT(11) NOT NULL AUTO_INCREMENT,
  `provider_id` INT(11) NULL DEFAULT NULL,
  `request_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`request_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`request_unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`request_unit` ;

CREATE TABLE IF NOT EXISTS `store`.`request_unit` (
  `request_unit_id` INT(11) NOT NULL AUTO_INCREMENT,
  `request_id` INT(11) NULL DEFAULT NULL,
  `module_id` INT(11) NULL DEFAULT NULL,
  `request_module_count` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`request_unit_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`role` ;

CREATE TABLE IF NOT EXISTS `store`.`role` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_type` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`sale` ;

CREATE TABLE IF NOT EXISTS `store`.`sale` (
  `sale_id` INT(11) NOT NULL AUTO_INCREMENT,
  `start_time` DATETIME NULL DEFAULT NULL,
  `end_time` DATETIME NULL DEFAULT NULL,
  `percentage_sale` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`sale_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`shipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`shipment` ;

CREATE TABLE IF NOT EXISTS `store`.`shipment` (
  `shipment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `provider_id` INT(11) NULL DEFAULT NULL,
  `way_bill_id` INT(11) NULL DEFAULT NULL,
  `cargo_margin_coefficient` DOUBLE NULL DEFAULT NULL,
  `is_processed` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`shipment_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`shipment_unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`shipment_unit` ;

CREATE TABLE IF NOT EXISTS `store`.`shipment_unit` (
  `shipment_unit_id` INT(11) NOT NULL AUTO_INCREMENT,
  `shipment_id` INT(11) NULL DEFAULT NULL,
  `module_id` INT(11) NULL DEFAULT NULL,
  `count` INT(11) NULL DEFAULT NULL,
  `cost` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`shipment_unit_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`state` ;

CREATE TABLE IF NOT EXISTS `store`.`state` (
  `state_id` INT(11) NOT NULL AUTO_INCREMENT,
  `state_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`state_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`storage_module_unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`storage_module_unit` ;

CREATE TABLE IF NOT EXISTS `store`.`storage_module_unit` (
  `storage_module_unit_id` INT(11) NOT NULL AUTO_INCREMENT,
  `module_id` INT(11) NULL DEFAULT NULL,
  `module_count` INT(11) NULL DEFAULT NULL,
  `unit_cost` DOUBLE NULL DEFAULT NULL,
  `date_of_delivery` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`storage_module_unit_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`user` ;

CREATE TABLE IF NOT EXISTS `store`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_id` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `surname` VARCHAR(50) NULL DEFAULT NULL,
  `login` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `store`.`waybill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `store`.`waybill` ;

CREATE TABLE IF NOT EXISTS `store`.`waybill` (
  `way_bill_id` INT(11) NOT NULL AUTO_INCREMENT,
  `shipment_id` INT(11) NULL DEFAULT NULL,
  `departure_date` DATETIME NULL DEFAULT NULL,
  `delivery_date` DATETIME NULL DEFAULT NULL,
  `delivery_cost` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`way_bill_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
